# Render configuration for CKD Prediction Tool
services:
  - type: web
    name: ckd-prediction-tool
    env: node
    region: ohio  # or choose your preferred region: oregon, frankfurt, etc.
    branch: main  # branch to auto-deploy from
    plan: free    # starter plan (upgrade for production)
    autoDeploy: true
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: "./dist"
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: CAPACITOR_BASE_URL
        value: https://ckd-prediction-tool.onrender.com
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html

# If you need a backend API later, you can add it like this:
#  - type: web
#    name: ckd-api
#    env: node
#    buildCommand: npm install
#    startCommand: node server.js
#    envVars:
#      - key: DATABASE_URL
#        fromDatabase:
#          name: ckd-db
#          property: connectionString
